name: flavors_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  flutter:
    sdk: flutter
  images:
    path: packages/images  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_flavorizr: ^2.2.3
  flutter_flavor: ^3.1.3

flutter:
  uses-material-design: true